spice_mix = set()
print(f"Initial spice mix id: {id(spice_mix)}")
print(f"Spice: {spice_mix}")
spice_mix.add("ginger")
spice_mix.add("cardamom")
print(f"Spice: {spice_mix}")
print(f"Spice mix after additions id: {id(spice_mix)}")